trigger:
  batch: true
  branches:
    include:
      - "APR-1634_shared_code_nuget"

variables:
  - name: buildConfiguration
    value: 'release'

jobs:
  - job: 'NugetPackage'
    pool:
      name: 'DAS - Continuous Integration'
    workspace:
      clean: all
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          updateAssemblyInfo: true

      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack'
        inputs:
          command: pack
          packagesToPack: |
            SFA.DAS.AdminService.Common/SFA.DAS.AdminService.Common.csproj
            SFA.DAS.AdminService.Common.Testing/SFA.DAS.AdminService.Common.Testing.csproj
          versioningScheme: byBuildNumber