trigger:
  batch: true
  branches:
    include:
      - "*"    

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildAndTest
    pool:
      name: 'DAS - Continuous Integration'
    steps:
    - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true
- stage: Test
  displayName: 'Test'
  jobs:
  - job: BuildAndTest
    pool:
      name: 'DAS - Continuous Integration'
    steps:
    - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true     