trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - group: "ESFA - SonarCloud"
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'

pool:
  name: 'DAS - Continuous Integration'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.37
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
