trigger:
  batch: true
  branches:
    include:
      - "*"    

variables:
  - group: "ESFA - SonarCloud"
  - name: sonarCloudProjectKey
    value: "SkillsFundingAgency_das-admin-service"
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildAndTest
    pool:
      name: 'DAS - Continuous Integration'
    steps:
    - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true
- stage: Test
  displayName: 'Test'
  jobs:
  - job: BuildAndTest
    pool:
      name: 'DAS - Continuous Integration'
    steps:
    - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true     